// v:11.1.4
var skimlinks_pub_id = '23432X820453';
var skimlinks_site = 'tipb.com';
var skimwords_hover_name = 'neutral';
var skimwords_horizontal_distance = 80;
var skimwords_vertical_distance = 80;
var noskimwords = true;
var noskoupon = true;
var noskimproducts = true;
var skimwords_instant = true;
(function(){var Ob,Pb,J,Qb,Rb,Sb,Tb,Ub,L,ib,Vb,Wb,jb,Xb,l,q,Yb,Zb,$b,kb,fa,ac,lb,mb,bc,t,cc,va,dc,k,wa,Na,nb,ec,fc,gc,hc,ob,m,x,xa,F,ga,M,ya,W,Oa,ha,j,N,ia,ja,p,ka,ic,G,la,pb,Pa,X,S,qb,za,Y,jc,kc,Qa,lc,Ra,Z,mc,nc,Aa,$,rb,oc,pc,qc,rc,sc,tc,Sa,uc,A,vc,wc,sb,ma,Ta,xc,Ua,Va,Ba,aa,tb,yc,ub,vb,wb,zc,xb,yb,Ac,zb,Bc,Wa,Cc,o,Ab,Dc,Ec,Fc,Gc,Ca,Hc,Ic,Jc,Kc,Da,Lc,Ea,na,Bb,Mc,Nc,Oc,Pc,Cb,Qc,Xa,D,Rc,Sc,Tc,Db,H,Uc,Fa,Ya,Za,Eb,ba,$a,T,Ga,Vc,U,V,oa,ab,Fb,Ha,R,bb,pa,cb,O,qa,B,E,ca,Wc,Xc,Yc,da,Zc,db,ea,Gb,$c,Ia,ad,
ra,eb,fb,bd,gb,C,Hb,Ib,sa,hb,Jb,v,r,Kb,ta,Ja,K,Ka,La,Ma,ua,I,Lb,cd,y,P,Mb,g,z={}.hasOwnProperty,Nb=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&this[b]===a)return b;return-1};W=Oa=null;ha=/http:/g;m=function(){return function(){var a;a=navigator.userAgent.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:parseFloat(a[2])||
0}}}(this)();X=[];Y=[];G={};pb=(new Date).getTime();la=[];ic=["buy.itunes.apple.com","itunes.apple.com","itunes.com"];Pa=[];N=F=M=null;ya=!1;ia=[];ga=[];ja=[];x={domains:[]};xa={};qa=O=bb=Ga=T=R=E=null;ba=[];V=[];U=cb=Za=$a=Ha=null;oa=!1;Fb="beginning";ab=[];B=ca=!1;Eb="skimlinksApplyHandlers";pa=!1;Ib=[];ua=La=Ma=Ka=I=null;v="";K=r=0;ta=Kb=Ja=Jb=Lb=!1;g=this;y=g.location;P="";J=!1;Ia=null;Ea={};hb=[];sa=ea=Gb=0;Ob=["noskim","norewrite"];Pb="*.g.doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com".split(",");
Vc=function(){return!0};Qa=function(a){var b;b=document.createElement("a");b.href=a;return da(b.hostname)};Vb=function(){var a,b,c,d,e,f,i,h,s,Q,n,l,w,u,m,k,o,q,t,v,x,z,A,C,D,F,G,H,J,L,M,N;Oa=null!=(a=document.getElementsByTagName("html"))?a[0]:void 0;ia=null!=(b=g.skimlinks_included_classes)?b:[];ga=null!=(l=g.skimlinks_excluded_classes)?l:[];ja=null!=(z=g.skimlinks_included_ids)?z:[];W=g.force_location?Qa(g.force_location):y.hostname;E=null!=(G=g.skimlinks_tracking)?G:!1;R=g.skimlinks_site||g.skimlinks_sitename||
!1;T=null!=(H=g.skimlinks_domain)?H:"go.redirectingat.com";Ga=null!=(J=g.skimlinks_google)?J:!1;bb=null!=Ga?Ga:"skimout";O=null!=(L=g.skimlinks_target)?L:!1;qa=null!=(M=g.sl_test)?M:!1;ba=null!=(N=g.skimlinks_exclude)?N:[];V=null!=(c=g.skimlinks_include)?c:[];Ha=null!=(d=g.skimlinks_noright)?d:!1;$a=null!=(e=g.skimlinks_exrel)?e:!1;Za=null!=(f=g.skimlinks_byrel)?f:!1;cb=null!=(i=g.skimlinks_blocked_tag)?i:!1;ca=null!=(h=g.skimlinks_revenue_forecast)?h:!1;pa=null!=(s=g.skimlinks_strip_attribute)?s:
!1;U=0;B=qc();g.skimlinks_revenue_forecast=!1;I=null!=(Q=g.skimlinks_pub_id)?Q:"";if(g.skimlink_legacy_support)g.skimlinks=function(){return!0},g.mugicPopWin&&(g._mugicPopWin=g.mugicPopWin),g.mugicPopWin=function(){return!0},g.mugicRight=function(){return!0},g.mugicRightClick=function(){return!0};r=null!=(n=g.skimlinks_dnt)?n:0;K=null!=(w=window.skimlinks_nocookie)?w:!1;K=null!=(u=window.skimlinks_nocookie)?u:!1;Ka=null!=(m=g.noimpressions)?m:!1;(La=null!=(k=g.noskimlinks||g.noskim)?k:!1)&&(S.skimlinks=
!1);(Ma=null!=(o=g.noskimwords||g.noskim)?o:!1)&&(S.skimwords=!1);ua=null!=(q=g.nounlinked||g.noskim)?q:!1;Ib=g.unlinked_excludes||[];ua&&(S.unlinked=!1);Lb=null!=(t=g.skim_toolbar)?t:!1;Jb=null!=(v=g.skimlinks_ajax_rerun)?v:!1;Kb=null!=(x=g.skimlinks_ipc)?x:!1;ta=null!=(A=g.skimlinks_ipc_diy)?A:!1;g._merchantSettings&&"undefined"===typeof replace_url_field?(Ja=!0,Eb="skimlinksApplyHandlersAlt"):Ja=!1;oa=null!=(C=g.skimlinks_ipc_decoration)?C:!1;Fb=null!=(D=g.skimlinks_ipc_position)?D:"beginning";
ab=null!=(F=g.skimlinks_ipc_domain_whitelist)?F:[];if(g.document&&g.document.referrer)P=g.document.referrer;Ac(W)&&(Ma=La=!0);E&&!/^[a-z0-9_\\|]+$/i.test(E)&&(E=!1);if("undefined"!==typeof p&&null!==p)p.pag=j.pag=g.force_location||y.href,p.pub=j.pub=I,p.uc=j.uc=E;"undefined"!==typeof assign_skimwords_globals&&null!==assign_skimwords_globals&&assign_skimwords_globals();ga.push("noskimlinks");Ia=document.createTextNode("").nodeName;return!0};cd=function(a,b){return a.hasOwnProperty(b)};qc=function(){var a;
return"function"===typeof(a=new Date).getTimezoneOffset?a.getTimezoneOffset():void 0};Ac=function(a){var b,c,d,e;if(g.noskim_domains){e=g.noskim_domains;for(c=0,d=e.length;c<d;c++)if(b=e[c],-1!==a.toLowerCase().indexOf(b.toLowerCase()))return!0}return!1};da=function(){return function(){var a;a=/^www\./i;return function(b){return b.replace(a,"")}}}(this)();q=function(){return function(){return document.addEventListener?function(a,b,c){if(a&&(a.nodeName||a===g))return a.addEventListener(b,c,!1)}:function(a,
b,c){if(a&&(a.nodeName||a===g))return a.attachEvent("on"+b,function(){return 7>m.version&&!window.event?(setTimeout(function(){return c.call(a,window.event)},100),!0):c.call(a,window.event)})}}}(this)();(function(){return function(){return document.createElement("div").getElementsByClassName?function(a,b){return A(a,b)?a:a.getElementsByClassName(b)}:function(a,b){var c;c=mb(b);return nb(a,c)}}})(this)();k=function(){return function(){var a,b;b=[function(){var b,d,e,f;e=[["%20","+"],["!","%21"],["'",
"%27"],["\\(","%28"],["\\)","%29"],["\\*","%2A"],["\\~","%7E"]];f=[];for(b=0,d=e.length;b<d;b++)a=e[b],f.push([RegExp(a[0],"g"),a[1]]);return f}()];return function(c){var d,e,c=encodeURIComponent(c);for(d=0,e=b.length;d<e;d++)a=b[d],c=c.replace(a[0],a[1]);return c}}}(this)();wb=function(){return function(){var a;a=/^\/\/|https?:\/\//i;return function(b,c){return a.test(b)&&(!c||!W||-1===c.indexOf(W))&&(!W||-1===W.indexOf("."+c))}}}(this)();l=function(a,b,c){var d;3<=arguments.length&&("undefined"!==
typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{return d=a[b],null==d&&(d=a.getAttribute(b)),d}catch(e){return null}};t=function(a,b,c){arguments[1]="data-"+b;return l.apply(this,arguments)};$c=function(a,b){var c;c=a.innerText||a.textContent||a.nodeValue;if(2<=arguments.length)"undefined"!==typeof a.innerText?a.innerText=b:a.textContent=b,c=b;return c};sb=function(a){return(""+a).replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")};C=function(){return function(){var a,
b;if(String.prototype.trim)return function(a){return null===a?"":String.prototype.trim.call(a)};a=/^\s+/;b=/\s+$/;/\S/.test("\u00a0")&&(a=/^[\s\xA0]+/,b=/[\s\xA0]+$/);return function(c){return null===c?"":c.toString().replace(a,"").replace(b,"")}}}(this)();Qb=function(a,b){return!A(a,b)?(a.className+=" "+b,!0):!1};Dc=function(a){var b,c,d,e,f;if("object"===typeof a||a instanceof Array){e="";d=0;c=a instanceof Array;for(f in a)z.call(a,f)&&(b=a[f],0<d&&(e+=","),c?e+=o(b):(b=o(b),e+='"'+f+'":'+b),d++);
return c?"["+e+"]":"{"+e+"}"}return"string"===typeof a?(b=a.replace(/"/g,'\\"',a),'"'+b+'"'):isNaN(a)?"null":a.toString()};o=function(){return function(){var a;return"undefined"!==typeof JSON&&null!==JSON&&JSON.stringify&&'["la"]'===JSON.stringify(["la"])?(a=JSON.stringify,function(b){return a(b)}):Dc}}(this)();wa=function(){return function(){var a,b;a=/[-[\]{}()*+?.,\\^$|#\s]/g;b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"s+")}}}(this)();mb=function(a){a=wa(a);return RegExp("\\b"+
a+"\\b","i")};A=function(a,b){return a.className?mb(b).test(a.className):!1};nb=function(a,b){var c,d,e,f,i;d=[];a.className&&b.test(a.className)&&d.push(a);i=a.childNodes;for(e=0,f=i.length;e<f;e++)c=i[e],d=d.concat(nb(c,b));return d};ac=function(a){return-1!==encodeURIComponent(a).indexOf("%C3%82%C2%A3")};hc=function(a){a=a.innerHTML.slice(0,4);if("http"===a||"www."===a)a.innerHTML="<span style='display:none!important;'>&nbsp;</span>";return!0};zb=function(a){for(var b,c,d,e;a&&a!==Oa;){c=a.id;
for(d=0,e=ia.length;d<e;d++)if(b=ia[d],A(a,b))return!1;for(d=0,e=ja.length;d<e;d++)if(b=ja[d],c===b)return!1;for(c=0,d=ga.length;c<d;c++)if(b=ga[c],A(a,b))return!0;a=a.parentNode}return ia.length||ja.length?!0:!1};aa=function(a,b,c){null==c&&(c=!1);for(b=RegExp("\\b(?:(?:"+wa(b)+")|(?:noskim))\\b","i");null!=a&&a!==Oa;){if(a.className&&b.test(a.className))return!0;a=c?null:a.parentNode}return!1};lb=function(a,b){var c,d,e,f,i,h;i=P?"&pref="+k(P):"";d=l(a,"data-skimlinks-editor")&&1===parseInt(l(a,
"data-skimlinks-editor"))?1:0;T=T||g.skimlinks_domain||"go.redirectingat.com";A(a,"skimwords-link")?(h=l(a,"data-skimwords-word"),c=l(a,"data-skim-creative"),e=l(a,"data-skim-product"),f=g.skimlinks_domain||"go.redirectingat.com","undefined"!==typeof settings&&null!==settings&&(f=settings.sw_domain||f),b="http://"+f+"/?id="+I+""+(E?"&xcust="+E:"")+"&xs=2&url="+k(b)+"&xguid="+v+"&isjs=1&xword="+(h?h:"")+"&xcreo="+(c?c:"")+"&xpid="+(e?e:"")+"&xed="+d+"&sref="+k(y)+""+i+""+(r?"&dnt="+r:"")+""+(K?"&fdnt=1":
"")+""+(!1!==B?"&xtz="+B:"")):A(a,"skimlinks-inline")?(c=l(a,"data-skim-creative"),b="http://"+T+"/?id="+I+""+(R?"&site="+R:"")+""+(qa?"&test="+qa:"")+""+(E?"&xcust="+E:"")+"&xs=8&isjs=1&url="+k(b)+"&xguid="+v+"&xcreo="+(a&&null!=c?c:0)+"&xed="+d+"&sref="+k(y)+"&pref="+k(P)+""+(r?"&dnt="+r:"")+""+(K?"&fdnt=1":"")+""+(!1!==B?"&xtz="+B:"")):aa(a,"noskimlinks")||(c=l(a,"data-skim-creative"),b="http://"+T+"/?id="+I+""+(R?"&site="+R:"")+""+(qa?"&test="+qa:"")+""+(E?"&xcust="+E:"")+"&xs=1&isjs=1&url="+
k(b)+"&xguid="+v+"&xcreo="+(a&&null!=c?c:0)+"&xed="+d+"&sref="+k(y)+""+i+""+(r?"&dnt="+r:"")+""+(K?"&fdnt=1":"")+""+(!1!==B?"&xtz="+B:""));J&&!aa(a,"noskimlinks")&&(b+="&abp=1");return b};Sa=function(a){var b,c,d;if(a.hasChildNodes()){d=a.childNodes;for(a=0,c=d.length;a<c;a++)if(b=d[a],b=Sa(b))return!0}else return Ua(a);return!1};Ua=function(a){var b,c,d,e,f;b=[[300,250],[302,252],[304,254],[300,300],[302,302],[304,304],[468,60],[470,62],[472,64],[728,90],[730,92],[732,94]];if(a&&a.nodeName&&"IMG"===
a.nodeName.toUpperCase()){d=a.offsetWidth||0;c=a.offsetHeight||0;for(e=0,f=b.length;e<f;e++)if(a=b[e],d===a[0]&&c===a[1])return!0}return!1};Ra=function(a){var b;if((b=a.target||a.srcElement)&&!b.href&&a.currentTarget)b=a.currentTarget;for(;b&&"A"!==b.nodeName.toUpperCase()&&"AREA"!==b.nodeName.toUpperCase();){if(Ua(b))return null;b=Aa(b)}return b};D=function(a){var b;b=Ra(a);if(!b||Sa(b))return!0;Cb(b);if(g.vglnk&&A(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=g.event,a.cancelBubble=
!0);return!0};Aa=function(a){for(;a.parentNode;){a=a.parentNode;if(Ua(a))break;if("A"===(null!=a?a.nodeName.toUpperCase():void 0)||"AREA"===(null!=a?a.nodeName.toUpperCase():void 0))return a}return null};Zc=function(a){return a=v?a.replace(/([&\?]{1})xguid=([a-fA-F0-9]{32})/,"$1xguid="+v):a.replace(/([&\?]{1}xguid=[a-fA-F0-9]{32})/,"")};Cb=function(a){var b,c,d,e,f;d=!1;e="msie"===m.browser&&7>m.version?1E4:300;b=Ga;a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&
(a=Aa(a));if(a){f=a.href;c="http://"+T;if(f.length>=c.length&&f.substr(0,c.length)===c)return!0;if("msie"===m.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;c=-1!==f.indexOf(c)?f:lb(a,f);b&&ad(f);t(a,"skimlinks-orig-link")||t(a,"skimlinks-orig-link",f);a.href=c;a.href=c;d&&a.innerHTML!==d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),300);setTimeout(function(){return function(){a.href=t(a,"skimlinks-orig-link");a.href=t(a,"skimlinks-orig-link");return t(a,
"skimlinks-orig-link","")}}(this),e)}return!0};tb=function(a,b){var c,d;null==b&&(b=Pa);if(b)for(c in b)if(z.call(b,c)&&(d=b[c],d===a))return!0;return!1};yb=function(a,b){return ca?(tb(a,b)&&(U+=1),!1):tb(a,b)};Cc=function(a){var b,c;if(!cb)return!1;b=null!=a?a.previousSibling:void 0;if(!b)return!1;a=("["+cb+"]").toLowerCase();c=$c(b);if(!c)return!1;c=c.toLowerCase();c=C(c);b=c.lastIndexOf(a);return-1!==b&&b+a.length===c.length};Ba=function(a){return!a||Za&&a===Za||!vc(a)};vc=function(a){var b,c,
d,e;M=null;if(!a)return!1;a=a.toLowerCase();if(M)return M[a];M={};b=$a?[$a]:[];b=b.concat(Ob);for(c=0,d=b.length;c<d;c++)e=b[c],M[e.toLowerCase()]=!0;return M[a]};kb=function(){var a,b,c,d;F={};N={};R&&ba.push(R);d=ba.concat(Pb);for(b=0,c=d.length;b<c;b++)a=d[b],F[a]=a.length;for(b=0,c=V.length;b<c;b++)a=V[b],N[a]=a.length;return F};ub=function(a){var b,c,d;(null===F||null===N)&&kb();if(!a)return!1;for(b in F)if(z.call(F,b))if(c=F[b],0===b.indexOf("*")){if(b=b.substr(1),c-=1,d=a.lastIndexOf(b),-1!==
d&&d===a.length-c)return!0}else if(a===b)return!0;return!1};zc=function(a){var b,c,d;(null===F||null===N)&&kb();if(!a)return!1;if(0===V.length)return!0;for(b in N)if(z.call(N,b))if(c="*"===b.substr(0,1),d="*"===b.substr(b.length-1,1),b=b.replace(/\*/g,""),c&&d){if(-1!==a.indexOf(b))return!0}else if(c){if(-1!==a.indexOf(b)&&a.indexOf(b)===a.length-b.length)return!0}else if(d){if(0===a.indexOf(b))return!0}else if(a===b)return!0;return!1};Va=function(a,b){return wb(a,b)&&!ub(b)&&zc(b)};Xa=function(a){if(10>
a)return la=Qc(),setTimeout(function(){return Xa(a+1)},2E3*a)};Qc=function(){var a,b,c,d,e,f,i;b={};d=[];c=[];for(e=0,f=la.length;e<f;e++)a=la[e],a.parentNode?c.push(a):b[a.href]=1;i=Z();for(e=0,f=i.length;e<f;e++)a=i[e],b[a.href]&&d.push(a);jb(d);return d.concat(c)};Rb=function(a,b){var c,d,e;d=[];ca&&(a.xrf=1);for(c in a)z.call(a,c)&&(e=a[c],"data"!==c&&d.push(""+c+"="+e));a.data&&d.push("data="+a.data);return b+"?"+d.join("&")};bd=function(a){a={call:"track",data:k('{"pubcode":"'+I+'", "referrer":"'+
y+'", "pref":"'+P+'", "site":"'+R+'", "url":"'+a+'", "custom":"'+E+'", "xtz":'+B+', "product":"1"}')};r&&(a.dnt=r);K&&(a.fdnt=1);a=Rb(a,"//t.skimresources.net/api/");a=a+"&rnd="+Math.random();nc(a);return!0};tc=function(a,b){var c,d,e;d=!1;c=Zc(b);if(c!==b&&(e="msie"===m.browser&&7>m.version?1E4:300,a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Aa(a)),a)){if("msie"===m.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;t(a,"skimlinks-orig-link")||
t(a,"skimlinks-orig-link",b);a.href=c;a.href=c;d&&a.innerHTML!==d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),300);setTimeout(function(){return function(){a.href=t(a,"skimlinks-orig-link");a.href=t(a,"skimlinks-orig-link");return t(a,"skimlinks-orig-link","")}}(this),e)}return c};Bb=function(a){var b,a=Ra(a);b=a.href;b.indexOf(T)&&(b=tc(a,b));bd(b);return!0};nc=function(a){var b,c;b=document.getElementsByTagName("body")[0];c=document.createElement("img");c.src=a;c.width=
1;c.height=1;if("undefined"!==typeof c.style)c.style.display="none";b.appendChild(c);return c};$=function(a,b,c){var n;var d,e,f,i,h;null==c&&(c={});d=c.charset||null;h=c.target||null;n=null!=(e=c.async)?e:!0,c=n;e=null!=h&&h.document?h.document:document;f=e.getElementsByTagName("head")[0];i=e.createElement("script");i.type="text/javascript";if(d)i.charset=d;if(b)i.onload=i.onreadystatechange=function(a){return function(){var c;c=!1;return function(){var d;d=a.readyState;if(!c&&(!d||"complete"===
d||"loaded"===d))return i.onload=i.onreadystatechange=null,c=!0,b.call(h),!0}}}(this)();i.async=!1!==c;i.src=a;f.appendChild(i);return i};Z=function(a,b){var c,d,e,f,i,h;e=null;a&&(e=RegExp("\\b"+wa(a)+"\\b","i"));h=[];b||(b=document);d=b.getElementsByTagName("a");for(f=0,i=d.length;f<i;f++){c=d[f];try{c.href&&(!e||c.className&&e.test(c.className))&&h.push(c)}catch(g){}}d=b.getElementsByTagName("area");for(f=0,i=d.length;f<i;f++){c=d[f];try{c.href&&(!e||c.className&&e.test(c.className))&&h.push(c)}catch(Q){}}return h};
xb=function(a){return-1!==a.indexOf("itunes.apple.com")||-1!==a.indexOf("itunes.com")||-1!==a.indexOf("phobos.apple.com")?!0:!1};Yc=function(a){var b,c,d;if(!pa)return!1;for(c in pa)if(cd(pa,c)&&(d=pa[c],(b=l(a,c))&&0===b.indexOf(d)))b=b.substr(d.length),l(a,c,b);return!0};jb=function(a){var b,c,d,e,f,i,h,g,Q;c=ia.length||ja.length||ga.length;e=[];for(g=0,Q=a.length;g<Q;g++)if(b=a[g],d=da(b.hostname),b.sl_hidden_domain&&(d=da(b.sl_hidden_domain)),h=C(b.href),i=l(b,"rel"),f=l(b,"onclick"),l(b,"sl-processed",
1),b["sl-processed"]=1,!Ja||!xb(h))if((!c||!zb(b))&&!Cc(b))if(yb(d)||xb(h)){if(Ba(i)){Yc(b);O&&l(b,"target",O);if("msie"===m.browser){if(ac(h))continue;hc(b)}null!=f&&-1!==f.toString().indexOf("return false")?q(b,"click",Nc):q(b,"click",D);db(b,!1);Ta(b);e.push(b);Ha||q(b,"contextmenu",D);Vc(b)}}else wb(h,d)&&!ub(d)&&Ba(i)&&(O&&l(b,"target",O),q(b,"click",Bb),Ha||q(b,"contextmenu",Bb));return e};Nc=function(a){var b;b=Ra(a);if(g._mugicPopWin)return g._mugicPopWin(b);D(a);return(O?window.open(b.href):
window.open(b.href,O)).focus()};Ta=function(a,b){var c,d,e,f,i,h,s,Q,n;if(g.link_icon||0<a.getAttribute("data-skim-product")&&g.skimwords_product_icon){if(0<a.getElementsByTagName("img").length)return!0;if("msie"===m.browser&&8>m.version)a.style.display="inline-block";f=d="";null!=b&&(d=g.skimwords_icon_class||"",f=g.skimwords_icon_link_class||"");i=l(a,"title").replace("'","&#39;");e=g.link_icon||g.skimwords_product_icon;A(a,"skimlinks-unlinked")||A(a,"skimwords-link")?(h='data-skim-creative="'+
t(a,"skim-creative")+'"',s='data-group-id="'+t(a,"group-id")+'"',n='data-skimwords-word="'+t(a,"skimwords-word")+'"',Q='data-skimwords-id="'+t(a,"skimwords-id")+'"',c=A(a,"skimlinks-unlinked")?"skimlinks-unlinked":"skimwords-link"):c=Q=n=s=h="";c="<a href='"+l(a,"href")+"' title='"+i+"' "+h+" "+s+" "+n+" "+Q+" style='border:0px;padding:0;margin:0' class='skimlinks-icon-link "+f+" "+c+"' skimlinked='skimlinked' target='_blank'><img src='"+e+"' class='"+d+"' skimlinked='skimlinked' style='margin: 0px 0px -3px 2px !important; float:none !important; border:0px; float:none !important; display:inline !important; width: auto !important; height: auto !important;' /></a>";
d=document.createElement("div");d.innerHTML=c;c=d.childNodes[0];q(c,"mousedown",D);a.appendChild(c)}return!0};pc=function(a,b){return null!=a.currentStyle?a.currentStyle[b]:window.getComputedStyle?document.defaultView.getComputedStyle(a,null).getPropertyValue(b):!1};ma=function(a,b){var c,d,e;for(d=0,e=b.length;d<e;d++)if(c=b[d],c===a)return!0;return!1};Db=function(a){var b,a=null!=a?a:{};null!=g.skimlinks_runner&&(g.skimlinks_runner.skimlinks=1);b=Z();a.guid&&""===v&&(v=a.guid);"undefined"!==typeof fb&&
null!==fb&&null!=x&&null!=x.domains&&fb(x.domains);Pa=a.merchant_domains||[];la=jb(b);U+=la.length;ua||Ab(a);Uc();return!0};Uc=function(){"undefined"!==typeof Fa&&null!==Fa&&(Kb||ta)&&Pa.length&&Fa();"undefined"!==typeof ra&&null!==ra&&ra("skimlinks");return!0};fc=function(){var a,b,c,d,e,f,i;d=Z();c=[];for(f=0,i=d.length;f<i;f++)a=d[f],b=da(a.hostname),e=C(a.href),a=l(a,"rel"),b&&Va(e,b)&&Ba(a)&&(G.hasOwnProperty(e)||(G[e]=0),G[e]++,xa[b]||(c.push(b),xa[b]=!0));return{domains:c}};Wb=function(){var a;
a=document.getElementsByTagName("body");if(0<a.length)return q(a[0],"click",L),q(a[0],"contextmenu",L)};L=function(a){var b,c,d;if(g.event)a=g.event;c=a.originalTarget||a.srcElement;try{if("A"!==(null!=c?c.nodeName.toUpperCase():void 0)&&c.parentNode)c=Aa(c)}catch(e){c=null}if(!c||Sa(c))return!0;try{b=l(c,"sl-processed")||0,null==c["sl-processed"]&&(b=0)}catch(f){b=0}if((d=l(c,"class"))&&(-1!==d.indexOf("skimwords-link")||-1!==d.indexOf("skimlinks-inline")||-1!==d.indexOf("skimlinks-unlinked")))b=
!0;if("A"===(null!=c?c.nodeName.toUpperCase():void 0)&&0===b)if(b=c,c=!0,!b||!b.href?c=!1:0!==b.href.indexOf("http://")&&0!==b.href.indexOf("https://")&&0!==b.href.indexOf("//")&&(c=!1),c&&Va(b.href,da(b.hostname))){Cb(b);if(g.vglnk&&A(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=g.event,a.cancelBubble=!0);return!0}};Kc=function(a){var b,c,d,e,f,i;b=k('{"pubcode":"'+I+'","domains":_DOMAIN_LIST_,"page":"'+y.href+'"}');e="//r2.skimresources.com/api/?callback="+Eb+(r?"&dnt="+r:"")+
(K?"&fdnt=1":"")+(Lb?"&call=toolbar":"")+"&data="+b;b="msie"===m.browser?2E3:8E3;d=[];for(f=0,i=a.length;f<i;f++)c=a[f],d.push(c),e.replace("_DOMAIN_LIST_",k(o(d))).length>b&&(d=d.slice(0,-1));e=e.replace("_DOMAIN_LIST_",k(o(d)));return $(e)};fa=function(a){var b,c;b=[];ca&&(a.xrf=1);for(c in a)a.hasOwnProperty(c)&&b.push(""+c+"="+k(a[c]));return b.join("&")};Ca=function(a,b,c){var d,e,f;if("msie"!==m.browser)e=!1,f=new XMLHttpRequest,f.open("POST",a,!0),f.setRequestHeader("Content-type","application/x-www-form-urlencoded"),
0<=Nb.call(f,"withCredentials")&&(f.withCredentials=!0),f.async="true",f.onreadystatechange=function(){var a;if(e)return!0;if(4===f.readyState){e=!0;if(200===f.status){a={};try{a=JSON.parse(f.responseText)}catch(b){try{a=eval("("+f.responseText+")")}catch(d){a={}}}c(a);return!0}return!1}},f.send(b);else if(g.XDomainRequest){if(d=new XDomainRequest,0<=Nb.call(d,"withCredentials")&&(d.withCredentials=!0),d){d.open("POST",a,!0);d.onload=function(){var a;a={};if("undefined"!==typeof JSON&&null!==JSON&&
JSON.parse)try{a=JSON.parse(d.responseText)}catch(b){a={}}else try{a=eval("("+d.responseText+")")}catch(e){a={}}c(a);return!0};d.onerror=function(){return!1};d.onprogress=function(){return!1};d.ontimeout=function(){return!1};d.async=!0;try{d.send(b)}catch(i){return!1}}}else return!1;return!0};Da=function(a){var b;b={data:o({pubcode:I,domains:a,page:y.href})};fa(b);Kc(a);return!0};Pc=function(){var a,b,c,d,e,f;c=Z();f=[];for(d=0,e=c.length;d<e;d++)(a=c[d])&&a.href?(b=Qa(a.href),0>Nb.call(ic,b)?(l(a,
"sl-processed",0),f.push(a["sl-processed"]=0)):f.push(void 0)):f.push(void 0);return f};Mb=function(){if(window.skimlinksInitialized&&"function"!==typeof post_skimwords_hook)return!0;window.skimlinksInitialized=!0;Vb();Ja&&Pc();Jb&&!La&&Wb();La||(x=fc(),ua&&Da(x.domains));"undefined"!==typeof Ya&&null!==Ya&&!ua&&Ya();"undefined"!==typeof skimwords&&null!==skimwords&&!Ma&&skimwords();return!0};H=function(){if(ya)return!1;ya=!0;dd.detect(function(a){J=a;return Mb()});return!0};Mc=function(a){var b,
c;b=0;for(c in a)z.call(a,c)&&(b+=1);return b};db=function(a,b){var c,d;d=a.style.cssText;""!==d&&(d+=" ");if(g.link_background)c=g.link_background,-1===c.indexOf("#")&&(c="#"+c),d+="background-color: "+c+" !important; ";if(null!=g.link_tooltip)a.title=g.link_tooltip;if(b){if(g.skimwords_color)c=g.skimwords_color,-1===c.indexOf("#")&&(c="#"+c),d+="color: "+c+" !important; ";g.skimwords_weight&&(d+="font-weight: "+g.skimwords_weight+" !important; ");if(g.skimwords_decoration)c=g.skimwords_decoration,
d="double"===c?d+"border-bottom: 1px double !important; ":"dashed"===c?d+"border-bottom: 1px dashed !important; ":d+("text-decoration: "+c+" !important; ");if(g.skimwords_style)c=g.skimwords_style,d+="font-style: "+c+" !important; ";if(g.skimwords_link_style)c=g.skimwords_link_style,d+=c+"; ";c=" "+a.className;if(g.skimwords_link_class)c+=" "+g.skimwords_link_class,a.className=c.substring(1);if(g.skimwords_title)a.title=g.skimwords_title;if(null===a.getAttribute("title"))a.title="Shopping link added by SkimWords";
if(a.getAttribute("data-skim-creative")&&(c=parseInt(a.getAttribute("data-skim-creative"))%10,1===c||2===c))a.title=""}a.style.cssText=d;return!0};Tc=function(){return function(){return function(){var a,b,c;if(window.skimlinks_revenue_forecast&&window.skimlinks)return!1;b=function(){if(ya)return!0;try{document.documentElement.doScroll("left")}catch(a){return setTimeout(b,50),!1}return H()};a=function(){return function(){return document.addEventListener?function(){document.removeEventListener("DOMContentLoaded",
a,!1);H();return!0}:document.attachEvent?function(){document.detachEvent("onreadystatechange",a);H();return!0}:function(){H();return!0}}}(this)();if("complete"===document.readyState)setTimeout(H,1);else if(document.addEventListener)document.addEventListener("DOMContentLoaded",a,!1),g.addEventListener("load",H,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",a);g.attachEvent("onload",H);c=!1;try{c=null===g.frameElement}catch(d){}document.documentElement.doScroll&&c&&b()}return!0}}}(this)();
cc=function(a,b){return setTimeout(b,a)};g.skimlinksApplyHandlers=Db;g.skimlinksApplyHandlersAlt=Db;g.skimlinksAjaxHandlerByClass=function(a){var b,c,d;if("function"===typeof document.getElementsByClassName){b=document.getElementsByClassName(a);for(c=0,d=b.length;c<d;c++)a=b[c],q(a,"click",L),q(a,"contextmenu",L);return!0}return!1};g.skimlinksAjaxHandlerById=function(a){return(a=document.getElementById(a))?(q(a,"click",L),q(a,"contextmenu",L),!0):!1};g.skimlinksRewriteUrl=lb;za=!1;ob=function(a){var b;
return a&&-1!==a.indexOf("class=")?(b=a.match(/([^\[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a:a};rc=function(a){Ea[a]=Ea[a]||0;Ea[a]++;return a+"_"+Ea[a]};Na=function(a){var b,c,d;b=c=null;-1!==a.indexOf(".")?(a=a.split("."),d=a[0],b=a[1]):-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[class^=")?(a=a.split("[class^="),d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],c=a[1].split("]"),c=c[0]):d=a;return{tag:d,
id:c,"class":b}};Wa=function(a,b){var c,d,e,f,i,g;e=b.split(",");for(i=0,g=e.length;i<g;i++){b=e[i];b=C(b);b=Na(b);f=!0;c=a.className||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"";d=("function"===typeof a.getAttribute?a.getAttribute("id"):void 0)||"";if(b.tag&&(!a.nodeName||a.nodeName.toLowerCase()!==b.tag))f=!1;if(b["class"]&&(!c||c!==b["class"]&&0!==c.indexOf(b["class"])))f=!1;if(b.id&&(!d||d!==b.id&&-1===d.indexOf(b.id)))f=!1;if(f)return!0}return!1};mc=function(a){var b,
c,d,e,f,i;if("undefined"!==typeof document.querySelectorAll)return document.querySelectorAll(a);e=[];a=Na(a);if(a.tag&&a["class"]){d=document.getElementsByTagName(a.tag);for(f=0,i=d.length;f<i;f++)b=d[f],(c=b.className||b.getAttribute("class"))&&0===c.indexOf(a["class"])&&e.push(b)}else a.tag&&a.id?(b=document.getElementById(a.id))&&b.nodeName.toLowerCase()===a.tag&&e.push(b):(a=a.tag,e=document.getElementsByTagName(a));return e};uc=function(a,b,c){var d,e,f,i,g;d=[];if("undefined"!==typeof a.querySelectorAll)d=
a.querySelectorAll(b);else if(b=Na(b),b.tag&&b["class"]){if(!a.getElementsByTagName)return c?[]:!1;f=a.getElementsByTagName(b.tag);for(i=0,g=f.length;i<g;i++)if(a=f[i],(e=a.className||a.getAttribute("class"))&&0===e.indexOf(b["class"]))if(c)d.push(a);else return!0}else if(b.tag&&b.id){if((a=document.getElementById(b.id))&&a.nodeName&&a.nodeName.toLowerCase()===b.tag)if(c)d.push(a);else return!0}else b=b.tag,d=a.getElementsByTagName(b);return c?d:0<d.length};vb=function(a,b){return 0===b.length?!1:
Wa(a,b.join(","))?!0:a.parentNode?vb(a.parentNode,b):!1};xc=function(a){var b;b=a.offsetWidth;a=a.offsetHeight;return 468===b&&60===a||234===b&&60===a||728===b&&90===a||300===b&&250===a||250===b&&250===a||336===b&&280===a||160===b&&600===a||120===b&&600===a?!0:!1};kc=function(){var a;a=[];a.push("div.widget-content");a.push("div.googleAdText");a.push("div[id=ad]");a.push("div[id=banner]");a.push("div[id=advertisement]");a.push("div[id=adv_container]");a.push("div.ad");a.push("div.banner");a.push("div.advertisement");
a.push("div.ad_container");a.push("span.IL_AD");a.push("div[id=fave-ext-container]");a.push("span.skimlinks-unlinked");-1!==y.href.indexOf(".google.")?(a.push("td.gac_c"),a.push("table[id=mbEnd]"),a.push("div[id=mbEnd]"),a.push("span[id=taw]"),a.push("td.std"),a.push("div.std"),a.push("table.gssb_e"),a.push("div.c"),a.push("div[id=tads]")):-1!==y.href.indexOf(".yahoo.")?(a.push("ul.spns,ul.reducepx-spnslist"),a.push("ul[class*=reducepx-spnslist]"),a.push("ul[id=east]")):-1!==y.href.indexOf(".aol.")?
(a.push("div.sllLink"),a.push("div.n")):-1!==y.href.indexOf(".bing.")&&(a.push("div.sb_adsW"),a.push("div[id=sidebar]"),a.push("div.sb_adsWv2"),a.push("div.sb_adsNv2"),a.push("div[class*=sb_ads]"));return a};Jc=function(a){var b,c,d,e;c={};for(d=0,e=a.length;d<e;d++)b=a[d],c[b]=!0;return c};na=function(){var a;a={};return{traverse:function(b,c,d,e){b=b||[];c=c||[];d=d||[];return a&&a.length&&!e?a:this.traverse_dom(b,c,d)},traverse_dom:function(b,c,d){var e,f,i,g,s,l,n,j;if(za)return a;za=!0;f=this.get_exclude_selector(c);
e=this.get_exclude_selector([]);c=f.selector;f=f.needed;e=e.selector;0===b.length&&b.push("body");b=b.concat(d);for(s=0,n=b.length;s<n;s++){i=b[s];i=ob(i);i=mc(i);for(g=l=0,j=i.length;l<j;g=++l)g=i[g],this.traverse_node(g,f,e,c,d)}return a},traverse_node:function(b,c,d,e,f){var g,h;h=[];g=0;for(h.push({node:b,tagName:"",readOnly:!1,parent_id:null});g<h.length;){if((b=h[g].node)&&!xc(b)&&!aa(b,"noskimwords",!0)&&(!c||!(""!==d&&Wa(b,d)))){h[g].readOnly=!1;if(b.nodeName&&b.nodeName!==Ia){h[g].tagName=
b.nodeName;if(null!==h[g].parent_id)h[g].readOnly=h[h[g].parent_id].readOnly;if(!h[g].readOnly)if(c&&Wa(b,e))h[g].readOnly=!0;else if(ma(b.nodeName.toLowerCase(),f))h[g].readOnly=!0;if(ma(b.nodeName.toLowerCase(),f))h[g].readOnly=!0}else if(null!==h[g].parent_id)h[g].tagName=h[h[g].parent_id].tagName,h[g].readOnly=h[h[g].parent_id].readOnly;"msie"===m.browser&&9>m.version&&h[g].readOnly||(b.hasChildNodes()?h=this.add_child_nodes(h[g],g,h):this._add(b,!1,h[g].tagName,h[g].readOnly))}g++}return a},
is_traversed:function(){return za},is_good_tag:function(a){return Jc("p,body,div,span,ul,ol,li,table,tbody,td,tr,th,tfoot,col,colgroup,em,strong,big,small,blockquote,cite,b,dl,dfn,dd,dt,ins,form,legend,noframes,pre,noscript,center,font,i,article,section".split(","))[a.nodeName.toLowerCase()]?!0:!1},is_html:function(a){return(a=C(a))&&"<"===a[0]},get_non_colliding_nodes:function(){var b,c,d;d=a;c={};Gb=0;for(b in d)z.call(d,b)&&(c[b]=d[b],Gb++);return c},get_as_hash_node_dict:function(){var b,c,d;
c={};for(b in a)d=a[b],a.hasOwnProperty(b)&&(c[b]=d);return c},get_as_pair_array:function(){var b,c;c=[];for(b in a)z.call(a,b)&&c.push([b,a[b]]);return c},get_exclude_selector:function(a,c){var d,e,f,g,h,s;g=[];if(!c){c=document.getElementsByTagName("body");if(!c.length)return{needed:!1,selector:""};c=c[0]}a=a.concat(kc());for(d=e=0,f=a.length;e<f;d=++e)a[d]=ob(a[d]);e=!1;f="";for(h=0,s=a.length;h<s;h++)d=a[h],uc(c,d,!1)&&g.push(d);g.length&&(e=!0,f=g.join(",").replace("class=","class^="));return{needed:e,
selector:f}},length:function(){return Mc(a)},reset:function(){a=[];return za=!1},add_child_nodes:function(a,c,d){var e,f,g,h;h=a.node.childNodes;for(f=0,g=h.length;f<g;f++)(e=h[f])&&e.nodeName&&(this._add(e,!1,a.tagName,a.readOnly)||this.is_good_tag(e)&&d.push({node:e,tagName:a.tagName,readOnly:a.readOnly,parent_id:c}));return d},add_node:function(a,c){return this._add(a,c)},_add:function(b,c,d,e){var f;f=null;b.nodeName===Ia&&(f=C(b.nodeValue));c=c||!1;if("msie"===m.browser&&9>m.version&&e)return!1;
if("msie"!==m.browser||9<=m.version)try{b.meta={ElementTag:d,ReadOnly:e}}catch(g){}if(f&&!this.is_html(f)&&3<=f.length){if(c&&"-1"===c)return!1;c=this._skim_id_hash(f,c);if(!c)return!1;a[c]=b}return f?!0:!1},_skim_id_hash:function(a){var c;if(!a)return"";c=C(a.replace(/\s+/g," ")).length;a=a.replace(/[:\s]*/g,"");c=""+c+":"+a.substring(0,20);return c=rc(c)}}}();Xc=function(a,b,c,d){var e,f,g,h,s,j,n,m,w,u,k;e=document.createDocumentFragment();n=0;m=[];k=b.nodeValue;h=[];s=b.parentNode;d||(d="skimwords-potential");
c||(c="-1");if(s){for(w=0,u=a.length;w<u;w++)g=a[w],j=document.createElement("span"),j.className=d,f=document.createTextNode(k.substring(n,g.start)),e.appendChild(f),j.innerHTML=g.text,e.appendChild(j),n={},n.node=j,n.match=g,l(n,"occurrence",g.target_occurrence),m.push(n),n=g.start+g.text.length,h.push(f),na.add_node(f,c);a=document.createTextNode(k.substring(n));h.push(a);e.appendChild(a);na.add_node(a,c);s.replaceChild(e,b)}return[m,h]};dc=function(a,b,c){var d,e,f;if(ca)return!1;d=(a.data?a.data:
a.childNodes[0].data).replace(b.repl_regex,b.replacement);f=document.createElement("span");b=document.createDocumentFragment();f.innerHTML=d;if("msie"===m.browser&&9>m.version&&(d=a.previousSibling,e=/^\s/,d&&d.nodeValue&&d.nodeValue.length&&e.test(d.nodeValue[d.nodeValue.length-1])&&(d.nodeValue+=" "),(d=a.nextSibling)&&d.nodeValue&&d.nodeValue.length&&e.test(d.nodeValue[0])))d.nodeValue=" "+d.nodeValue;for(;f.firstChild;)f.firstChild.nodeName===Ia?(d=b.appendChild(f.firstChild),na.add_node(d)):
(d=b.appendChild(f.firstChild),null!==d&&!c&&(db(d,!0),Ta(d,!0)));if(c=a.parentNode)return c.replaceChild(b,a)};Ec=function(a,b){10>parseInt(b)&&(b="0"+b);return"3"+a+"0"+b};Ub=function(a,b){1E7<a&&6!==b&&(a-=1E7);return a};Sc=function(a,b,c){var d,e,f;f=b.phrase;d={};d.w=f.text();d.lp=f.url();if(c)d.t=Hb,e="unlinked";else{if(0===f.limit())return!1;f.dec_limit();ea+=1;d.ed=f.is_editor()?1:0;d.t=Ec("02",f.action_type(),f.group_id());e="skimwords";d.pid=0===f.group_id()?0:Ub(f.id(),f.action_type())}Tb(d,
e);dc(a,b,c);return!0};Hb="500005";Yb=function(a){q(a,"click",D);Ha||q(a,"contextmenu",D);db(a,!1);return Ta(a)};wc=function(a){a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig.exec(a);return a.length&&""!==a[0]?!0:!1};jc=function(a,b,c,d){var e,f;e=wa(a);f="";O&&(f='target="'+O+'"');b=sb(b);e="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+e+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";a='$1$2<a href="'+b+'" class="'+d+'" '+f+' data-skimwords-word="'+
encodeURIComponent(sb(a))+('"  data-skim-creative="'+c+'" title="">$3$4</a>$5$6');b=e.replace(/\?:/g,"");return{search_regex:RegExp(e,"i"),repl_regex:RegExp(b,"i"),repl_text:a}};Xb=function(){var a,b,c,d,e;b=Z("skimlinks-unlinked");e=[];for(c=0,d=b.length;c<d;c++)a=b[c],e.push(Yb(a));return e};Ab=function(a){var b,c,d,e;b={};if((c=a.merchant_domains)&&c.length){for(d=0,e=c.length;d<e;d++)a=c[d],b[a]=!0;for(d=0,e=hb.length;d<e;d++)c=hb[d],a=c.match.domain,b.hasOwnProperty(a)&&Sc(c.node,c.match,!0)}cc(10,
function(){return Xb("skimlinks-unlinked")});try{return ra("unlinked")}catch(f){return!0}};ec=function(a,b){var c,d,e,f,g,h,s,l,n,j,k;if(!a||vb(a,["span.skimlinks-unlinked"]))return[[],[]];k=a.data;e=[];h=[];for(n=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig;d=n.exec(k);)if(c=d[0],"link.phrase"!==c)if(g=d.index,0<C(c).length&&-1===c.indexOf("/.")&&-1===c.indexOf("..."))f=c,0!==c.indexOf("http")&&0!==c.indexOf("//")&&(f="msie"===m.browser&&6>=m.version?
"http://"+c:"//"+c),d=Qa(f),l=bc({OriginalPhrase:""+c,Url:f,Title:"",ActionType:2,GroupId:0,Unlinked:!0}),(j=jc(""+c,f,Hb,"skimlinks-unlinked"))&&h.push({start:g,text:""+c,domain:d,repl_regex:j.repl_regex,replacement:j.repl_text,regex:j.search_regex,phrase:l,link:f}),e.push(d);else break;if(h.length){s=Xc(h,a,b,"skimlinks-unlinked");c=s[0];s=s[1];for(n=0,k=c.length;n<k;n++)h=c[n],hb.push(h)}s||(s=[]);return[e,s]};Rc=function(a){var b,c,d;if(ba.length)for(c=0,d=ba.length;c<d;c++)if(b=ba[c],b===a)return!1;
if(V.length){for(c=0,d=V.length;c<d;c++)if(b=V[c],b===a)return!0;return!1}return!0};sc=function(){var a,b,c,d,e,f;c=na.get_as_hash_node_dict();for(b in c)if(a=c[b],a.parentNode&&!zb(a)&&!aa(a,"noskimwords")&&!aa(a,"noskimlinks")&&!aa(a,"noskimw")&&(!a.meta||!a.meta.ReadOnly)){a=ec(a,b);f=a[0];for(d=0,e=f.length;d<e;d++)a=f[d],!xa[a]&&Rc(a)&&(xa[a]=!0,x.domains.push(a))}return x.domains.length?Da(x.domains):ra("unlinked")};Ya=function(){var a;a=document.getElementsByTagName("body");a.length?(a=a[0].textContent||
a[0].innerText)&&wc(a)?Ma?(na.traverse([],Ib,[]),sc()):getSkimwordsData("skimwordsSettingsCallback"):x.domains.length&&Da(x.domains):x.domains.length&&Da(x.domains)};g.skimlinksUnlinked=Ab;p={pag:"",pub:"",guid:"",uc:"",lnks:{}};ka={};$b=function(a,b){var c,d,e;e="GBP"===a.currency?"&pound;":"EUR"===a.currency?"&euro;":"$";d=document.createElement("a");l(d,"href",a.url);l(d,"title",a.title);l(d,"target","_blank");Qb(d,"skimlinks-inline");l(d,"data-skim-creative",b);c=0;ta&&(c=1);l(d,"data-skimlinks-editor",
c);c=parseFloat(Math.round(100*a.price)/100).toFixed(2);d.innerHTML=""+a.merchant+" "+e+c;q(d,"mousedown",D);return d};Zb=function(a,b,c,d,e){return"8"+("text"===a?"1":"cross"===a?"2":"blink"===a?"3":"0")+b+c+(d-1)+e};lc=function(a,b){var c,d,e,f,g,h,l;c=b.price;if(!c)return"0";d=0;e=1E8;g=0;for(h=0,l=a.length;h<l;h++)f=a[h],f=parseFloat(f.price),f>d&&(d=f),parseFloat(f)<e&&(e=f),f===c&&g++;return 1<g?"4":c>=d?"3":c<=e?"1":"2"};Wc=function(a,b,c){var d,e,f,g,h;e=!1;for(d=g=0,h=a.length;g<h;d=++g)if(f=
a[d],f.url===c){e=d;break}e&&(c=a[e],"beginning"===b?(a[e]=a[0],a[0]=c):"end"===b&&(a[e]=a[a.length-1],a[a.length-1]=c));return a};Oc=function(a){var b,c;if("1"===l(a,"ipc-added")){for(;")"!==(null!=(c=a.nextSibling)?c.textContent.substring(0,1):void 0);)(b=a.nextSibling)&&b.parentNode&&b.parentNode.removeChild(b);if(a&&a.parentNode&&a.nextSibling)return a.parentNode.removeChild(a.nextSibling)}};Sb=function(a,b,c,d,e,f,i){var h,j,k,n,m,w,u,p,o,q,t,r,v,x;Oc(b);k=!0;m=b;n=!1;c=Wc(c,Fb,d);e.hasOwnProperty(d)?
(w=e[d],f[w].cnt++):(i[d]={},w={},w.lpid=d,w.cnt=1,w.url=b.href.replace(ha,""),w.prd=[],w.ed=ta?1:0,f.push(w),w=f.length-1,e[d]=w);"cross"===oa?l(b,"style","text-decoration: line-through !important;"):"text"===oa?null!=b.parentNode&&(e=null!=(p=pc(b.parentNode,"color"))?p:"#000",l(b,"style","color: "+e+" !important; text-decoration: none !important;")):"blink"===oa&&l(b,"style","text-decoration: blink !important;");e=c.length;p=0;if(g.skimlinks_editor)v=b.parentNode,r=document.createElement("span"),
t=document.createElement("span"),h=b.cloneNode(!0),r.appendChild(h),r.appendChild(t),r.style.display="inline !important",r.classList.add("sl-select-wrapper"),t.classList.add("sl-select-products"),h.classList.add("sl-select-link");for(h=0,x=c.length;h<x;h++){u=c[h];n=!0;q=u.currency+u.price+u.url+u.title+u.merchant;p+=1;j=lc(c,u);j=Zb(oa,j,e,a,p);if(!i[d].hasOwnProperty(q))o={},o.cur=u.currency,o.mn=u.merchant,o.mid=u.merchant_id,o.pr=u.price,o.ti=u.title,o.pu=u.url.replace(ha,""),o.cr=j,f[w].prd.push(o),
i[d][q]=!0;u=$b(u,j);k?(q=document.createTextNode(" ("),k=!1):q=document.createTextNode(" | ");g.skimlinks_editor?(t.appendChild(q),t.appendChild(u)):(m.parentNode.insertBefore(q,m.nextSibling),q.parentNode.insertBefore(u,q.nextSibling));m=u}g.skimlinks_editor&&v.replaceChild(r,b);k||(a=document.createTextNode(") "),m.parentNode.insertBefore(a,m.nextSibling));l(b,"ipc-added",1);return n};Bc=function(a,b,c){var d,e;for(e in b)if(z.call(b,e)&&(d=b[e],e===a&&(0===d.length||ma(c,d))))return!0;return!1};
ib=function(a){var b,c,d,e,f,g,h,j,k,n,m;if(!a)return!1;d={};e=[];g={};c=[];j=!1;for(k in a)if(z.call(a,k)&&ka.hasOwnProperty(k)&&(h=a[k],h.length)){f=ka[k];for(n=0,m=f.length;n<m;n++)b=f[n],k=C(b.href),l(b,"rel"),Sb(1,b,h,k,d,e,g)&&(j=!0),c.push({url:k,occurrence:l(b,"data-occurrence"),products:h})}j&&"undefined"!==typeof eb&&null!==eb&&eb(e);"undefined"!==typeof setSelectLinks&&null!==setSelectLinks&&setSelectLinks(c);return!0};oc=function(){var a;a="//ipc.skimresources.com/api/select_whitelist.php?callback=selectWhitelistCallback&data="+
k(o({pubcode:I,page:y.href}));return $(a)};Hc=function(a){var b,c,d,e,f,g;e="//ipc.skimresources.com/api/select.php?callback=selectCallback&urls=";b="msie"===m.browser?2E3:8E3;c=[];for(f=0,g=a.length;f<g;f++)d=a[f],c.push(d),d=k(o(c)).length,d+e.length>b&&(c=c.slice(0,-1));if(c.length)return e+=k(o(c)),$(e)};Ic=function(a){var b;b={urls:o(a),debug:1};b=fa(b);(J||!Ca("//ipc.skimresources.com/api/select.php",b,ib))&&Hc(a);return!0};rb=function(a){var b,c,d,e,f,g,h,j,k,n,m,o,p,q,r;if(!1!==a&&0===a.length)return!1;
m=[];g={};h=Z();k=0;for(o=0,q=h.length;o<q;o++)if(b=h[o],e=da(b.hostname),n=C(b.href),j=l(b,"rel"),d=b.childNodes,!ab.length||ma(e,ab)){if(d&&d.length){f=!1;for(p=0,r=d.length;p<r;p++)c=d[p],c.nodeName&&"IMG"===c.nodeName.toUpperCase()&&(f=!0);if(f)continue}if(Va(n,e)&&Ba(j)&&yb(e)&&(g.hasOwnProperty(n)||(g[n]=0),g[n]++,l(b,"data-occurrence",g[n]),l(b,"data-select-id",k),k++,!a||Bc(n,a,g[n])))if(c=l(b,"class"),!c||!(-1!==c.indexOf("skimlinks-inline")||-1!==c.indexOf("skimwords-link")))if("undefined"===
typeof ka[n]&&(ka[n]=[]),ka[n].push(b),ma(n,m)||m.push(n),100<=m.length)break}return 0===m.length?!1:Ic(m)};Fa=function(){return ta?oc():rb(!1)};g.selectCallback=ib;g.selectWhitelistCallback=rb;g.skimlinksApplySelect=Fa;bc=function(a){var b,c,d,e;d=b=null;c=5;a.Limit&&(c=a.Limit);e=function(){return a.Priority||0};return{group_id:function(){return b?b.id():0},dec_limit:function(){return c-1},limit:function(){return c},action_type:function(){return a.ActionType},text:function(){return a.OriginalPhrase},
start_byte:function(){return a.StartByte},url:function(){return a.Url},multi:function(){return a.Mt?!0:!1},is_editor:function(){return null!=a.ValidOn&&""!==a.ValidOn?!0:!1},is_blacklisted:function(){return null!=a.IsBlacklisted?a.IsBlacklisted:!1},group_priority:function(){return b?b.group_priority():e()},id:function(){return d?d:a.PhraseId},groups:function(){var b;return(b=a.Groups)?b:[]},title:function(){return a.Unlinked?"":a.ActionTitle?a.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(b){return a.Unlinked?
a.Title="":a.Title=b},occurrence:function(){return a.PhraseOccurrence},set_group:function(a){return b=a},set_id:function(a){return d=a}}};j={pag:"",phr:[],unl:[],pub:"",slc:0,swc:0,ulc:0,jsl:0,jsf:"",guid:"",uc:"",t:1};S={skimlinks:!0,skimwords:!0,unlinked:!0};qb=!1;Tb=function(a,b){var c,d,e,f;c=!0;if("skimwords"===b){for(e=0,f=X.length;e<f;e++)if(d=X[e],c=d.pid?d.pid===a.pid:d.w===a.w)return c;X.push(a)}else if("unlinked"===b){for(e=0,f=Y.length;e<f;e++)d=Y[e],d.w===a.w&&(c=!1);c&&Y.push(a);sa++}return c};
Gc=function(){var a,b,c,d,e,f;a=8E3;"msie"===m.browser&&(a=2E3);d={};d.guid=v;d.pub=I;d.pag=y.href;d.tz=B;d.dl={};d.typ="l";c="//t.skimresources.net/api/link?data=";f=0;for(e in G)z.call(G,e)&&(b=G[e],f++,d.dl[e]=b,b=c+k(o(d)),b.length>a&&(f--,delete d.dl[e]));f&&(c+=k(o(d)),$(c,!1,{async:!0}));return!0};yc=function(a){for(var b in a)if(z.call(a,b))return!1;return!0};fb=function(){var a;if(Ka||yc(G))return!1;a={};a.guid=v;a.pub=I;a.pag=y.href;a.dl=G;a.tz=B;a.typ="l";a={data:o(a)};r&&(a.dnt=r);K&&
(a.fdnt=1);a=fa(a);if(J||!Ca("//t.skimresources.net/api/link",a,gb))return Gc()};ad=function(a){var b,c,d;b=g.pageTracker;d=g.urchinTracker;c="/"+bb+"/"+a;if(null!=b&&b._trackPageview)return b._trackPageview(c),!0;if(d)return d(c),!0;if(g._gaq)b=g._gaq,b.push(["_trackEvent",bb,"click",a]);return!1};Fc=function(a){var b,c,d,e,f;p.tz=B;p.guid=v;p.pref=P;p.lnks=[];p.typ="s";b=8E3;"msie"===m.browser&&(b=2E3);c="//t.skimresources.net/api/ipc?data=";for(e=0,f=a.length;e<f;e++)d=a[e],p.lnks.push(d),d=c+
k(o(p)),d.length>b&&(p.lnks=p.lnks.slice(0,-1));p.lnks.length&&(c+=k(o(p)),$(c,!1,{async:!0}));return!0};eb=function(a){var b;if(Ka)return!1;p.tz=B;p.guid=v;p.pref=P;p.lnks=a;p.typ="s";b={data:o(p)};b=fa(b);(J||!Ca("//t.skimresources.net/api/ipc",b,gb))&&Fc(a);return!0};gb=function(){return!0};ra=function(a){var b,c;if(Ka||qb)return!1;S[a]=!1;a=!0;for(b in S)if(z.call(S,b)&&(c=S[b],!0===c)){a=!1;break}if(a)return qb=!0,gc()};va=function(a){var b,c,d,e,f;if(a instanceof Array){c={};for(b=e=0,f=a.length;e<
f;b=++e)d=a[b],c[""+b]=d;return c}return a};Lc=function(){var a,b,c,d,e;a=(new Date).getTime()-pb;b=8E3;"msie"===m.browser&&(b=2E3);j.tz=B;j.slc=U;j.swc=null!=ea?ea:0;j.ulc=null!=sa?sa:0;j.jsl=a;j.guid=v;j.pref=P;j.phr=[];j.unl=[];ca&&(j.xrf=1);a="//t.skimresources.net/api/track.php?";r&&(a=a+"dnt="+r+"&");K&&(a+="fdnt=1&");J&&(a+="abp=1&");a+="data=";for(c=d=0,e=X.length;d<e;c=++d)c=X[c],j.phr.push(c),c=a+k(o(j).replace(ha,"")),c.length>b&&(j.phr=j.phr.slice(0,-1));for(c=d=0,e=Y.length;d<e;c=++d)c=
Y[c],j.unl.push(c),c=a+k(o(j).replace(ha,"")),c.length>b&&(j.unl=j.unl.slice(0,-1));j.phr=va(j.phr);j.unl=va(j.unl);b=a+k(o(j).replace(ha,""));$(b,!1,{async:!0});return Xa(1)};gc=function(){var a;a=(new Date).getTime()-pb;j.tz=B;j.slc=U;j.swc=null!=ea?ea:0;j.ulc=null!=sa?sa:0;j.jsl=a;j.guid=v;j.pref=P;a=j;a.phr=va(X);a.unl=va(Y);a={data:o(a)};r&&(a.dnt=r);K&&(a.fdnt=1);a=fa(a);if(J||!Ca("//t.skimresources.net/api/track.php",a,gb))return Lc(),!0;null!=g.skimlinks_runner&&(g.skimlinks_runner.tracking=
1);Xa(1);return!0};!g.mugicPopWin&&!g.skimlink_legacy_support&&!g.skimlinks_revenue_forecast&&(g.mugicPopWin=D);!g.mugicRight&&!g.skimlink_legacy_support&&!g.skimlinks_revenue_forecast&&(g.mugicRight=D);g.skimlinksReload=function(){ya=!1;H();return!0};!g.skimlink_legacy_support&&!g.skimlinks_revenue_forecast&&(g.skimlinks=Mb);var dd=new function(a){function b(a,c){e||1E3<c?"function"==typeof a&&(e?d?a(!0):a(!1):a(!1)):setTimeout(b,c*=2,a,c)}function c(){e||(f.complete&&g.complete&&(e=!0),e&&"0"!=
f.width&&"0"==g.width&&(d=!0))}var d=!1,e=!1,f=null,g=null;this.detect=function(a){b(a,250)};(function(){try{var b=navigator.userAgent.toLowerCase();if(-1==b.indexOf("firefox")&&-1==b.indexOf("chrome")){e=!0;d=!1;return}}catch(j){}b=11*Math.random();f=new Image;f.onload=c;f.src=a.replace(/\*/,1).replace(/\*/,b);g=new Image;g.onload=c;g.src=a.replace(/\*/,2).replace(/\*/,b)})()}("//p.skimresources.net/px.gif?ch=*&rn=*");Tc()})();
